### ISSUE TITLE
[Question]Publish in the Chrome Web Store?

### ISSUE THREAD

**Issue by zhongfly** [Baldomo/open-in-mpv#10]
Is it possible to publish this web extension in Chrome Web Store? If so, it would be more convenient to install or update.

**Comment by Baldomo** [comment]
It may be done in the future but it's a lot of work (more so than maintaining the Mozilla Addons page) and I've had several bad experiences with getting Google accounts banned after publishing extremely trivial apps/extensions for generic reasons on Google's part. The general lack of transparency, asa developer, really makes me want to avoid contact with Google distribution platforms as much as possible. That said, I still publish the signed `.crx` file in the releases, so it should be a 1-click install on Chromium-based browsers. I may add a link to the repo in the settings page/popup window so users can easily check for updates, would that be useful?
