### ISSUE TITLE
Doesn't make on linux "missing separator"

### ISSUE THREAD

**Issue by GalileoBlues** [Baldomo/open-in-mpv#11]
If i try to sudo make install it errors giving me "missing separator", removing the Windows and Mac parts allows me to make the program then it works flawlessly.
![2022-05-20_21-05](https://user-images.githubusercontent.com/105921721/169520348-4c35af63-5f8c-4165-a3cc-3bb635970282.png)

Edit: seems to be that line 20 has a link that's not formatted correctly

**Comment by Baldomo** [comment]
I use Linux fulltime and GNU Make works on my end. Is your editor changing tabs to spaces or something like that?

```shell
```

**Comment by Baldomo** [comment]
Since no one has reported this issue nor have I received uodates here, I will be closing/archiving this for the time being. Anyone who whishes to respond to will have the issue reopened.
