### ISSUE TITLE
VSC status error when building on Fedora 36

### ISSUE THREAD

**Issue by tandy-1000** [Baldomo/open-in-mpv#12]
Here is the error:

```
$ sudo make install

# Building for Linux
env CGO_ENABLED=0 GOOS=linux GOARCh=amd64 go build -ldflags="-s -w" -o build/linux/open-in-mpv ./cmd/open-in-mpv
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
make: *** [Makefile:11: build/linux/open-in-mpv] Error 1
```

**Comment by Baldomo** [comment]
Hi, sorry for the late response! It seems like you may have a `.git` directory laying around where it shouldn't be, have you tried building the project in another directory (for example `/tmp`)? I cannot reproduce this error in any way, even in a Fedora VM.

See golang/go#49004 and/or golang/go/53640 for more information, maybe you can find something useful there. Let me know!
