### ISSUE TITLE
switch from URL handler to native messaging?

### ISSUE THREAD

**Issue by pabs3** [Baldomo/open-in-mpv#13]
Have you considered switching from using a URL handler to launch the video player to using native messaging instead? The advantage would be that websites and other extensions cannot access access the URL handler any more, only the `open-in-mpv` extension would be able to do that, so it would be a fair bit more secure. The native messaging feature is supported by [Firefox](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Native_messaging), [Chrome](https://developer.chrome.com/docs/apps/nativeMessaging/), [Edge](https://docs.microsoft.com/microsoft-edge/extensions-chromium/developer-guide/native-messaging) and [Safari](https://developer.apple.com/documentation/safariservices/safari_web_extensions/messaging_between_the_app_and_javascript_in_a_safari_web_extension). Unfortunately I don't know Go so I couldn't help implement this, but the documentation does make it look fairly simple to implement.

**Comment by pabs3** [comment]
i think this would fix issue #7 too.

**Comment by Baldomo** [comment]
First of all, thank you for the suggestion. After testing the binary in native extension, I decided against it and in favour of strict URL scheme validation in the player configuration. Deploying the native manifest would be too much of a hassle without having a dedicated installer (and that would need to be platform-specific), not to mention it leaves files hanging around in the browsers' folders. Anyone is more than welcome to try implementing this idea and send a PR, but I will archive this for the time being.

**Comment by pabs3** [comment]
OK, I might try to do this, since I would only be using this extension
as a Debian package and in that context, deployment will be easy and
the files would be removed when the extension package is removed.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
