### ISSUE TITLE
feature: Executing with shortcut

### ISSUE THREAD

**Issue by toprak** [Baldomo/open-in-mpv#17]
### Feature Description

Like qutebrowser has when i click the , button it spawns umpv, so yeah hope you got it. 
### Code Snippet (optional)

```Go
package main
import "log"

func main() {
  // An example to describe the feature
  log.Println("Hello world!")
}
```

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by Baldomo** [comment]
Could you please give a more in-depth explanation of your idea with practical examples (e.g. a video recording or a drawing)? This feature sounds way too specific to me to be implemented extension-wide in any case, but we shall see.
