### ISSUE TITLE
README: please mention https://github.com/belaviyo/send-to-vlc and describe the difference

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Baldomo/open-in-mpv#35]
https://github.com/belaviyo/send-to-vlc

Despite the name - it also works for mpv, and it works for me.

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by Baldomo** [comment]
Thank you for the idea, but I don't think that will be necessary. I'm happy that extension works for you, but it's a different project and looks to be unmaintained.
