### ISSUE TITLE
How do I make it work?

### ISSUE THREAD

**Issue by Tuxiis** [Baldomo/open-in-mpv#36]
### Question Description

Hello, I hope I make myself understood, I am using Google Translate.

1 download the linux.tar file (zip) maybe I don't remember anymore

2 run without administrator permissions, ./install-protocol.sh

3 install the plugin to firefox 131.0.3 (snap) (default on ubuntu-mate 24.04)

4 I used the plugin on youtube, it doesn't work, I put config.yml in ~/.config/open-in-mpv/, (the one that comes by default from github), it didn't work.

5 I used chatgpt to help me, I took each step of github, and we came to the following conclusion. Edit config.yml, it didn't work.

[OPEN-IN-MPV.zip](https://github.com/user-attachments/files/17536788/OPEN-IN-MPV.zip)

### Code Snippet (optional)

```Go
package main
import "log"

func main() {
  // An example to describe the feature
  log.Println("Hello world!")
}
```

### Checklist:

- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by Baldomo** [comment]
Hi! You should try with another browser (or again with Firefox) but NOT installed using snap. Snap does weird stuff to programs, especially browsers. I've had problems with native extensions in the past in browsers installed with snap.

**Comment by Baldomo** [comment]
Closing for lack of feedback
