### ISSUE TITLE
feature: move to MV3

### ISSUE THREAD

**Issue by arthsmn** [Baldomo/open-in-mpv#39]
### Feature Description

This can lead to heavy refactoring but it's necessary as [chrome web store doesn't support MV2 anymore](https://developer.chrome.com/docs/extensions/mv2?hl=pt-br) and it'll be [deprecated soon](https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline?hl=pt-br). Recently, [ff2mpv did migrate](https://github.com/woodruffw/ff2mpv/commit/7b6c4d825fa89f0699166cd746eaa7024795f24f), so it seems doable.

### Checklist:

- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by Baldomo** [comment]
This will be released in the next update. Thanks! It was harder than expected though, documentation is all over the place and Firefox followed a slightly different spec than the Chrome one.
