### ISSUE TITLE
Using Celluloid as player mpv flags ignored

### ISSUE THREAD

**Issue by jsjuris89** [Baldomo/open-in-mpv#4]
```
[juris@juris-aspiree1571 ~]$ xdg-open 'mpv:///open?url=/home/juris/Downloads/episode1.mp4&player=celluloid&flags=--start=360%20--end=363'
[juris@juris-aspiree1571 ~]$ 
** (io.github.celluloid_player.Celluloid:103712): WARNING **: 23:06:05.163: --mpv-options is deprecated and will be removed in future versions.
** (io.github.celluloid_player.Celluloid:103712): WARNING **: 23:06:05.386: Failed to apply option: --start=360--mpv-options=end=363
```
Just launches video in Celluoid. `flags=` is ignored.
![celluoid-error](https://user-images.githubusercontent.com/53792052/107159557-86f44400-6999-11eb-9430-8a0e03b0fe39.png)

If I try just `xdg-open 'mpv:///open?url=/home/juris/Downloads/episode1.mp4&player=celluloid&flags=--start=360` it works, but for example, 
`xdg-open 'mpv:///open?url=/home/juris/Downloads/episode1.mp4&player=celluloid&flags=--end=4'` doesn't work, are some MPV lags not supported in Celluloid?

**Comment by Baldomo** [comment]
Sorry for getting back to you only now, that's correct. I've been testing Celluloid flags lately as I also use it as a general purpose video player and the deev team is refusing support for mpv flags and such. I'm looking for a workaround for a possible next release.
