### ISSUE TITLE
bug: link with player=undefined

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Baldomo/open-in-mpv#40]
### Bug Description

![2024-dec-22--04-34-17_maim](https://github.com/user-attachments/assets/81b65e71-e059-492b-9d47-ba8af71d6b46)

![image](https://github.com/user-attachments/assets/8f998b57-f125-4462-b7d2-07c169f4e77f)

### How to Reproduce

Installed the extension
Click the button

### Expected Behavior

player=mpv

### Version

2.4.0

### Configuration

```yml
Where to find it?
```

### What browsers are you seeing the problem on? (optional)

Firefox-based (Librewolf, Iceraven, etc.)

### Checklist:

- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by Baldomo** [comment]
Working on it! Will be fixed asap
