### ISSUE TITLE
ytdl-format string interprented as multiple arguments

### ISSUE THREAD

**Issue by user18130814200115-2** [Baldomo/open-in-mpv#7]
With mpv, you can pass a ytdl-format option allowing for selection f resolutions and audio quality.
If you do this with this extension, the + signs (which are part of the format string) are interpreted and separate out the arguments.

For example:
`ytdl-format=bestvideo[height<=480]+bestaudio`
becomes
`--ytdl-format=bestvideo[height<=480] bestaudio`

For celluloid (with default config), the string becomes:
`--mpv-ytdl-format=bestvideo[height<=480] --mpv-bestaudio`

**Comment by user18130814200115-2** [comment]
I just found this can be fixed by encoding the `+` as `%2B`,
so perhaps his is more of a documentation issue.

**Comment by Baldomo** [comment]
Could you try escaping the `+` with `\+`? It sounds like the way `encodeURIComponent` works clashes with how Go's `url.QueryUnescape()` works.

**Comment by Baldomo** [comment]
I could not reproduce this bug in recent versions, could you please check for yourself?

**Comment by user18130814200115-2** [comment]
Looks resolved, thanks!
