### ISSUE TITLE
Ubuntu 20.04.4 LTS compatibility 

### ISSUE THREAD

**Issue by tristan-k** [Baldomo/open-in-mpv#8]
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

```
./open-in-mpv                     
./open-in-mpv: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./open-in-mpv)
``` 

Is there a way to make the extension compatible with `Ubuntu 20.04.4 LTS`?

**Comment by Baldomo** [comment]
Should be fixed now, thanks! Since `CGO_ENABLED` was left unset, the executable required GLIBC. I'll push out a new minor release which should work on your platform.
