### ISSUE TITLE
Black square

### ISSUE THREAD

**Issue by jimmy-1000** [Baldomo/open-in-mpv#9]
Hi, is there a way to hide or not to show the black square when I open any video?
This CLI or black window is of course from mpv.com. May be if you binary calls to mpv.exe instead mpv.com?

I use latest mpv and Firefox
Windows 7 64 bits.

**Comment by Baldomo** [comment]
The default configuration does indeed call mpv.exe I believe, but you can tweak it yourself as documented in the README if you want a quick fix. I do have to test the configuration on Windows a little more, so I will roll a fix before the next release. Thank you for the bug report!

**Comment by steponmepls** [comment]
Alternatively you can rename mpv.com to something else and make a symbolic link called mpv.com that redirects to mpv.exe with `mklink .\mpv.com .\mpv.exe`. You need admin permissions to make such a link and it might get overwritten with mpv updates.

**Comment by jimmy-1000** [comment]
> Alternatively you can rename mpv.com to something else and make a symbolic link called mpv.com that redirects to mpv.exe with `mklink .\mpv.com .\mpv.exe`. You need admin permissions to make such a link and it might get overwritten with mpv updates.

If mpv.com is deleted or rename, 'open-in-mpv' works fine without the black square. But mpv.com is necessary in Windows if you want to control and use many features of mpv via CMD. I thought about moving a copy of mpv.exe to another location, but I can't link 'open-in-mpv' to that new location.

**Comment by jimmy-1000** [comment]
> ...

Sadly last version 2.1.0 doesn't work with Windows 7 64 bits.

**Comment by Baldomo** [comment]
After some thought, and some improvements to the exiting codebase, I decided that this issue no longer stands. This problem can be solved by either specifying the executable suffix (or full path), or creating a custom .bat script which runs the actual executable with other flags or settings or creates directories (you get me). Additionally, the fullscreen bug has been fixed and Windows builds in general have been reworked a little
